version = 1

[[analyzers]]
name = "javascript"
enabled = true

[[analyzers]]
name = "php"
enabled = true

[[transformers]]
name = "prettier"
enabled = true

[[transformers]]
name = "php-cs-fixer"
enabled = true